// Weather
export const FETCH_WEATHER_START = "FETCH_WEATHER_START";
export const FETCH_WEATHER_SUCCESS = "FETCH_WEATHER_SUCCESS";
export const FETCH_WEATHER_FAILURE = "FETCH_WEATHER_FAILURE";
export const FETCH_FORECAST_START = "FETCH_FORECAST_START";
export const FETCH_FORECAST_SUCCESS = "FETCH_FORECAST_SUCCESS";
export const FETCH_FORECAST_FAILURE = "FETCH_FORECAST_FAILURE";
export const SET_CURRENT_LOCATION = "SET_CURRENT_LOCATION";
export const SET_SAVED_CITIES = "SET_SAVED_CITIES";
export const ADD_SAVED_CITY = "ADD_SAVED_CITY";
export const REMOVE_SAVED_CITY = "REMOVE_SAVED_CITY";

// Auth
export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAILURE = "AUTH_FAILURE";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
export const AUTH_SET_USER = "AUTH_SET_USER";

// UI
export const SET_THEME = "SET_THEME";
export const SET_UNITS = "SET_UNITS";
export const SHOW_TOAST = "SHOW_TOAST";
export const HIDE_TOAST = "HIDE_TOAST";
export const SET_LOADING = "SET_LOADING";
export const SET_SEARCH_QUERY = "SET_SEARCH_QUERY";
export const SET_SEARCH_RESULTS = "SET_SEARCH_RESULTS";
export const ADD_RECENT_SEARCH = "ADD_RECENT_SEARCH";
